import { StyleSheet } from 'react-native';

export const colors = {
  background: '#425896',
  backgroundSecondary: '#8180c2',
  backgroundTertiary: '#231d5b',
  black: '#000',
  lightGold: '#edc8a2',
  mediumGold: '#edb76f',
  darkGold: '#c7853d',
  lightBlue: '#9e99de',
  mediumBlue: '#655ec4',
  darkBlue: '#2F2897',
  trueYellow: '#DFC74F',
  buttonDisabledBackground: '#999999',
  buttonDisabledBorder: '#dddddd',
  brickRed: '#84495A',
  trueRed: '#C84B58',
  orange: '#DC7C51',
  darkPurple: '#572E5C',
  mediumPurple: '#845B8A',
  placeholderText: '#7a7a7a'
}

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    alignItems: 'center',
  },
  logo: {
    width: '85%',
    height: '20%',
    resizeMode: 'contain',
  },
  inputView: {
    flex: 1,
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 100,
  },
  buttonRowContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  modalView: {
    margin: 20,
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 20,
    padding: 35,
    height: 300,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  input: {
    height: 50,
    width: 250,
    padding: 10,
    borderWidth: 1,
    borderColor: 'grey',
    borderRadius: 10,
    backgroundColor: 'white',
    fontSize: 24,
  },
  marginedInput: {
    height: 50,
    width: 250,
    padding: 10,
    marginTop: 15,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: 'grey',
    borderRadius: 10,
    backgroundColor: 'white',
    fontSize: 24,
  },
  nameContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  flatList: {
    backgroundColor: colors.backgroundTertiary,
    marginTop: 20,
    marginBottom: 10,
    padding: 5,
    paddingBottom: 20,
    flexGrow: 0,
    width: 300,
    height: 300,
    borderWidth: 2,
    borderColor: colors.lightGold,
    borderRadius: 10,
  },
  scoreboardButtonContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    margin: 2.5,
  },
  scoresListContainer: {
    backgroundColor: colors.background,
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
    marginTop: 60,
  },
  individualScoresListContainer: {
    maxWidth: 115,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  scoresList: {
    backgroundColor: colors.backgroundTertiary,
    margin: 5,
    padding: 5,
    flexGrow: 0,
    width: 100,
    height: 275,
    borderWidth: 2,
    borderColor: colors.lightGold,
    borderRadius: 10,
  },
});

export const text = StyleSheet.create({
  mainText: {
    color: 'white',
    fontFamily: 'Trebuchet MS',
    fontSize: 36,
  },
  buttonText: {
    color: 'white',
    fontFamily: 'Trebuchet MS',
    fontSize: 25,
  },
  playerList: {
    color: 'white',
    fontFamily: 'Trebuchet MS',
    fontSize: 36,
    paddingLeft: 5,
  },
  smallCentered: {
    display: 'flex',
    color: 'white',
    fontFamily: 'Trebuchet MS',
    fontSize: 18,
    textAlign: 'center',
  },
  modalText: {
    color: 'white',
    fontFamily: 'Trebuchet MS',
    fontSize: 24,
    textAlign: 'center',
  },
  score: {
    color: colors.lightGold,
    fontFamily: 'Trebuchet MS',
    fontSize: 20,
    textAlign: 'center',
  },
  scoreHistory: {
    color: 'white',
    fontFamily: 'Trebuchet MS',
    fontSize: 25,
    paddingLeft: 5,
  },
  finalJeopardyTitle: {
    color: 'white',
    fontFamily: 'Trebuchet MS',
    fontSize: 36,
    marginBottom: 20,
    textAlign: 'center',
    marginTop: 100,
  },
});

export const buttons = StyleSheet.create({
  newGameButton: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    backgroundColor: colors.mediumGold,
    width: 275,
    height: 60,
    borderRadius: 10,
    borderColor: colors.darkGold,
    borderWidth: 3,
    margin: 50,
  },
  addPlayerButton: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    backgroundColor: colors.lightBlue,
    borderRadius: 10,
    borderColor: 'white',
    borderWidth: 3,
    margin: 10,
    padding: 20,
    maxHeight: 75,
  },
  nextButton: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    backgroundColor: colors.darkGold,
    borderRadius: 10,
    borderColor: colors.lightGold,
    borderWidth: 3,
    margin: 10,
    padding: 20,
    maxHeight: 75,
  },
  disabledButton: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.buttonDisabledBackground,
    borderRadius: 10,
    borderColor: colors.buttonDisabledBorder,
    borderWidth: 3,
    margin: 10,
    padding: 20,
    maxHeight: 75,
  },
  modalButton: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    backgroundColor: colors.lightBlue,
    borderRadius: 10,
    borderColor: 'white',
    borderWidth: 3,
    margin: 10,
    padding: 10,
    maxHeight: 75,
    width: 120,
  },
  smallModalButton: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    backgroundColor: colors.lightBlue,
    borderRadius: 10,
    borderColor: 'white',
    borderWidth: 3,
    margin: 5,
    padding: 5,
    width: 120,
    height: 50,
  },
  wager: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    backgroundColor: colors.lightBlue,
    borderRadius: 10,
    borderColor: 'white',
    borderWidth: 3,
    margin: 5,
    padding: 5,
    width: 100,
  },
  deleteButton: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'red',
    width: 20,
    height: 20,
    marginRight: 10,
    borderRadius: 20,
  },
  playerButton: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    backgroundColor: colors.lightBlue,
    borderRadius: 20,
    width: 175,
    padding: 5,
    margin: 5,
    borderWidth: 3,
  },
  score: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    backgroundColor: colors.trueYellow,
    borderRadius: 20,
    width: 150,
    padding: 7,
    margin: 5,
    borderWidth: 3,
  },
  doubleJeopardy: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    backgroundColor: colors.brickRed,
    borderRadius: 20,
    width: 150,
    height: 45,
    padding: 5,
    margin: 5,
  },
  negativeScore: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    backgroundColor: colors.trueRed,
    borderRadius: 20,
    width: 40,
    padding: 7,
    margin: 5,
  },
  dailyDouble: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    backgroundColor: colors.orange,
    borderRadius: 20,
    width: 150,
    height: 45,
    padding: 5,
    margin: 5,
  },
  submitScore: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    backgroundColor: colors.darkGold,
    borderRadius: 20,
    width: 200,
    padding: 7,
    margin: 5,
    borderColor: colors.lightGold,
    borderWidth: 3,
  },
  finalJeopardy: {
    justifyContent: 'center',
    color: 'white',
    backgroundColor: colors.darkPurple,
    borderRadius: 20,
    width: 170,
    padding: 7,
    margin: 5,
    borderColor: colors.mediumPurple,
    borderWidth: 3,
  },
  currentGameHistory: {
    justifyContent: 'center',
    color: 'white',
    backgroundColor: colors.darkBlue,
    borderRadius: 20,
    width: 170,
    padding: 7,
    margin: 5,
    borderColor: colors.mediumBlue,
    borderWidth: 3,
  },
  exitGame: {
    justifyContent: 'center',
    color: 'white',
    backgroundColor: colors.trueRed,
    borderRadius: 20,
    width: 170,
    padding: 7,
    margin: 5,
    borderColor: colors.brickRed,
    borderWidth: 3,
  }
});
