import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#425896',
    alignItems: 'center',
  },
  logo: {
    width: '85%',
    height: '20%',
    resizeMode: 'contain',
  },
  inputView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 100,
  },
  buttonContainer: {
    flex: 0.75,
    justifyContent: 'space-around',
    alignItems: 'center',
    flexDirection: 'row',
  },
  modalView: {
    margin: 20,
    backgroundColor: '#8180c2',
    borderRadius: 20,
    padding: 35,
    height: 300,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  input: {
    height: 50,
    width: 250,
    marginTop: 20,
    marginBottom: 20,
    padding: 10,
    borderWidth: 1,
    borderColor: 'grey',
    borderRadius: 10,
    backgroundColor: 'white',
    fontSize: 24,
  },
  nameContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  flatList: {
    backgroundColor: '#231d5b',
    marginTop: 20,
    marginBottom: 10,
    padding: 5,
    paddingBottom: 20,
    flexGrow: 0,
    width: 300,
    height: 300,
    borderWidth: 2,
    borderColor: '#edc8a2',
    borderRadius: 10,
  },
});

export const text = StyleSheet.create({
  mainText: {
    color: 'white',
    fontFamily: 'Trebuchet MS',
    fontSize: 36,
  },
  buttonText: {
    color: 'white',
    fontFamily: 'Trebuchet MS',
    fontSize: 28,
  },
  playerList: {
    color: 'white',
    fontFamily: 'Trebuchet MS',
    fontSize: 36,
    paddingLeft: 5,
  },
  maxPlayers: {
    display: 'flex',
    color: 'white',
    fontFamily: 'Trebuchet MS',
    fontSize: 18,
    marginLeft: 20,
    marginRight: 20,
    textAlign: 'center',
  },
  modalText: {
    color: 'white',
    fontFamily: 'Trebuchet MS',
    fontSize: 24,
    textAlign: 'center',
  },
});

export const buttons = StyleSheet.create({
  newGameButton: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    backgroundColor: '#edb76f',
    width: 275,
    height: 60,
    borderRadius: 10,
    borderColor: '#c7853d',
    borderWidth: 3,
    margin: 50,
  },
  addPlayerButton: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    backgroundColor: '#9e99de',
    borderRadius: 10,
    borderColor: 'white',
    borderWidth: 3,
    margin: 10,
    padding: 20,
    maxHeight: 75,
  },
  nextButton: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    backgroundColor: '#c7853d',
    borderRadius: 10,
    borderColor: 'white',
    borderWidth: 3,
    margin: 10,
    padding: 20,
    maxHeight: 75,
  },
  disabledButton: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    backgroundColor: 'grey',
    borderRadius: 10,
    borderColor: 'white',
    borderWidth: 3,
    margin: 10,
    padding: 20,
    maxHeight: 75,
  },
  modalButton: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    backgroundColor: '#9e99de',
    borderRadius: 10,
    borderColor: 'white',
    borderWidth: 3,
    margin: 10,
    padding: 10,
    maxHeight: 75,
    width: 120,
  },
  smallModalButton: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    backgroundColor: '#9e99de',
    borderRadius: 10,
    borderColor: 'white',
    borderWidth: 3,
    marginTop: 20,
    marginLeft: 20,
    marginRight: 20,
    padding: 10,
    width: 120,
    height: 50,
  },
  deleteButton: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'red',
    width: 20,
    height: 20,
    marginRight: 10,
    borderRadius: 20,
  },
});
